
hello:
		gcc hello-world.c -o hello -levent

test:
		gcc test.cpp -o test -levent

myread:
		gcc myread.cpp -o myread -levent

mywrite:
		gcc mywrite.cpp -o mywrite -levent

server:
		gcc server.cpp -o server -levent
		
client:
		gcc client.cpp -o client -levent