serverEpoll:
		gcc serverEpoll.cpp -lpthread -o serverEpoll -Wall -g -std=c99
serverEpollET:
		gcc serverEpollET.cpp -lpthread -o serverEpollET -Wall -g -std=c99

client:
		gcc client.cpp -lpthread -o client -Wall -g -std=c99

et:
		gcc ET.cpp -lpthread -o et -Wall -g -std=c99